spring:
  devtools:
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:login_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog/changelog-master.xml'
