version: '3.8'
services:
  student-grading-micronaut:
    image: student-grading-micronaut-image
    container_name: student-grading-micronaut-app
    build:
      context: .
      dockerfile: Dockerfile-Prod
    env_file: .env
    ports:
      - ${APPLICATION_PORT_ON_DOCKER_HOST}:${APPLICATION_PORT_ON_CONTAINER}
    volumes:
      - ./:/java-workspace/student-grading-app
    depends_on:
      - db
    networks:
      - student-grading-network

  db:
    container_name: student-grading-db
    image: postgres:14.1-alpine
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${DB_PORT_ON_DOCKER_HOST}:${DB_PORT_ON_CONTAINER}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - student-grading-network

volumes:
  db:

networks:
  student-grading-network: