micronaut:
  server:
    port: 8080
  application:
    name: studentGradingMicronaut

db:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  name: ${DB_NAME:student_db}
  user: ${DB_USER:postgres}
  password: ${DB_PASSWORD:postgres}

datasources:
  default:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    driverClassName: org.postgresql.Driver
    username: ${db.user}
    password: ${db.password}
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
      packages: in.one2n.studentgrading.entity

jpa.default.properties.hibernate.hbm2ddl.auto: none

liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'

netty:
  default:
    allocator:
      max-order: 3